Feature/a
Yuwen-ctw/simple_twitter pull request #13
Opened 2022-12-17 18:08 UTC by whps40333

有簡化authInput，找到格式化的方法(按下ctrl+shift+p，再選Format document with prettier)。
有注意到onchange後面可以用大括號掛載多個函式，所以想掛一個function是檢查length>50，另一個functon則是用switch切換錯誤訊息的case。目前卡在想不到當字數超過50，要怎麼傳true或false或任何props，給另一個function去進行switch判斷，然後印error message，明天會再繼續嘗試。

2022-12-17 22:31 UTC, Yuwen-ctw commented on src/components/form/AuthInput.jsx
> +        id="profile-AuthInput-textInput"
AuthInput重構成1個共用元件時，要注意到每一個html元素的id屬性都具有唯一性，因此應避免讓元件有共用的id。
可以考慮把id裡面的字串裝props變數傳進去。

2022-12-17 22:33 UTC, Yuwen-ctw commented on src/components/form/AuthInput.jsx
> -const EmailInput = forwardRef((props, ref) => {
若input密碼元件若要移除，請考慮原本就有存在的屬性值，並將該屬性值移至共用元件上，例如autoColplete。

2022-12-17 22:35 UTC, Yuwen-ctw commented on src/pages/LoginPage.jsx
> +function LoginPage({ user }) {
這裡想接收一個user prop的考量是什麼呢?

2022-12-17 22:37 UTC, Yuwen-ctw commented on src/pages/LoginPage.jsx
> +import { useState, useEffect, useRef } from 'react'
此檔案目前未發現用到useRef的程式碼，猜測你是要用在 RegisterPage而不是這裡，請修正。

2022-12-17 22:38 UTC, Yuwen-ctw commented on src/pages/RegisterPage.jsx
> +  const refnameInput = useRef(null)
目前refnameInput 沒有程式碼用到它，請釐清。
若要使用，請在檔案上方引入 useRef。

2022-12-17 22:38 UTC, Yuwen-ctw commented on src/pages/RegisterPage.jsx
> +  const [showErr, setShowErr] = useState(false)
此二變數沒有被使用，猜測與line 91~93有關係，請釐清。

2022-12-17 22:49 UTC, Yuwen-ctw requested changes
以這份commit啟動專案會出現錯誤，原因是RefisterPage有沒有宣告就使用的變數，請處理。

有關輸出error message，可參考以下流程：
1. 寫一個函式可以捕捉input的當下value值
2. 透過value.length 得到字串總長度
3. 以 if 判斷式判斷是否超過規範
4. 超過規範需要重新渲染畫面，因此可考慮使用 useState，故此元件最頂層宣告useState，並設定其為布林值  (我在其他地方不一定這麼做，但你可以先從這裡下手)
5. 承3，超過規範限制則使用 setState(true)，更新state
6. 於RegisterPage元件最下方return JSX的地方，將state以props傳進AuthInput裡面
7. 在AuthInput裡面就可以接收布林值，並進行樣式變化。

建議先確定單一input可以發揮作用，在考慮用switch進行重構。

2022-12-18 16:37 UTC, whps40333 commented on src/pages/RegisterPage.jsx
> +function RegisterPage({ user }) {
不知道為什麼有宣告user但讀不到name的值

2022-12-18 22:57 UTC, Yuwen-ctw commented on src/components/form/AuthInput.jsx
> +      <label htmlFor={id}>{label}</label>
啟動專案後，畫面顯示  'id' is not defined 
代表你有變數沒有宣告就被使用了。
觀察AuthInput.jsx，會發現Line 14使用id變數，但Line 11 卻沒有對應的props，因此若要讓此元件可以存取id，請把id加進Line 11裡

2022-12-18 23:32 UTC, Yuwen-ctw commented on src/pages/RegisterPage.jsx
> +function RegisterPage({ user }) {
這裡要先瞭解的是，RegisterPage想要讀取的user是誰? 用途是什麼?

先回到你的問題，有關於為何讀不到user這件事，有個觀念是，RegisterPage是一個function component，如果此 function 內部有變數可以運用，可能有三種來源:
1. 全域變數
2. 元件內自己宣告的變數
3. 呼叫function 時傳遞下來的參數
而目前你想取用的user程式碼，是使用第三種來源的取用方式。

然RegisterPage 是由Router.jsx 的<Route>進行調用的，且調用時也沒提供任何參數給RegisterPage，因此你無法用第三種方式取得user。

而解法並不是去Router新增user變數給RegisterPage，而是先思考前述第一個問題，這個user是誰?
可能你心中的答案是正在嘗試註冊的使用者本人，於是我的下一個問題是，要取得使用者本人的name要做甚麼?
以及此元件甚麼時候可以取得使用者本人的name?

依照你程式碼的邏輯，你可能想透過user.name 存進inputValues變數裡面，讓此元件可以控制name這個變數，作為後續判斷字數或送出api的功能。
但由於你是在useState的初始化時就想存取user.name，而此頁面初始化時，並沒有user資訊，自然無法取出name。

此元件真正能拿到使用者名稱的時機，是使用者自己於input 標籤上進行輸入的時候，而input標籤是RegisterPage的子元件，因此若要取用name，應該是從input元件。

修改的位置可從兩處下手：
1. 將inputValues的初始值改為空字串(Line 15)
2. 在呼叫setInputValue這個函式，也就是handleInputChange裡，第32行所使用的引數不對，原本引數應該是一個物件，你嘗試利用擴展運算子把物件展開，這樣與初始值的樣子不符合。
建議先把Line29~31註解掉，並透過console觀察 inputValue是否能取得使用者輸入的name，成功後再進行後續判斷。

2022-12-23 03:51 UTC, Yuwen-ctw reviewed
接手此版本並調整後上傳。

2022-12-23 03:51 UTC, closed without merging